Exception Handling :
-------------------------
- Errors - We cant handle them.
   StackoverFlow, OutOfMemory
   Optimize Program or increase memory size are solutions for the Errors
- Exceptions - We can handle programatically. test
    Ex: ClassCastException, NumberFormatExceptions, ArrayIndexOutOfBound, IllegalArgumentException, NullPointerException.

               Exception
                  |
        --------------------------------------------------------------------------------------
       |                                                                                     |
  CompileTimeExceptions(Classes which extends Exception class)                     RuntimeExceptions(Classes which extends RuntimeException class)
       |                                                                                     |
   FileNotFoundException, UrlNotFoundExceptions...       ClassCastException, NumberFormatExceptions, ArrayIndexOutOfBound, IllegalArgumentException, NullPointerException.

Keywords:
try, catch, throws, throw, finally
thrown
try:
   try{
        //exception suspected sequence of statements.
        int j, int k
        int i = j/k;
        //lets assume j is 5, and k is 0
   }catch(ArithmeticException ex){
       sout("Dont give zero value as input for division")
   }

Create a Method, that accepts 2 integer params.
   try to divide them.
   keep the division code in try catch block
   write main method and invoke it with non exception scenario and exception scenario.

---------------------------------
Custom Exception:
-----------------
It is a normal class, It will extend either Exception class or RuntimeException class to become custom Exception

//It will generates Compiletime Exception
Class DivideByZeroError extends Exception{

}

//It will generates Runtime Exception
Class DivideByZeroError extends RuntimeException{

}

If we are having CompileTime Exception in our block of code, then we have 2 choices.

1. We need handle the exception in try, catch
2. We need to make the exception Class to be declared in method signature.( we use throws)

Throw:
  throw new CustomException;

1. Create Exception class
2. Copy the same class we did try catch
3. In catch use our throw syntax to throw a exception.
4. main method and then call the implemented method.



Throws and Throw:
-------------------

